version: '2'
services:
  web:
    build: lila
    links:
     - db1
    volumes:
     - ..:/lila
     - ivy-data:/root/.ivy2
    ports:
     - "9663:9663"
  opening_explorer:
    build: opening_explorer
    volumes:
     - opening-explorer-data:/root/.ivy2
     - opening-explorer-code:/lila
    ports:
     - "9000:9000"
  db1:
    image: mongo:3.2
    ports:
     - "27017:27017"
    volumes:
     - mongo-data:/data/db
  nginx:
    build: nginx
    links:
     - db1
     - web
    volumes:
     - ..:/home/user/lila
    extra_hosts:
     - l.org en.l.org de.l.org le.l.org fr.l.org es.l.org l1.org socket.en.l.org socket.le.l.org socket.fr.l.org ru.l.org el.l.org hu.l.org socket.hu.l.org:127.0.0.1
    ports:
     - "80:80"
  fishnet:
    image: ageneau/fishnet
    links:
     - nginx
volumes:
  mongo-data:
    driver: local
  ivy-data:
    driver: local
  opening-explorer-data:
    driver: local
  opening-explorer-code:
    driver: local
